Makefile
It isn’t part of the repository, so the Makefile should not rely
on it being present.
Fixes #19.
=> Ensure that the css directory exists

docker/Dockerfile, docker/entrypoint.sh, web_config.production.py
Add a Dockerfile to allow to have snikket-web-portal in a Docker container. It can then be added to the docker-compose.yml file and be run next to the Snikket container.
I did not know about Hypercorn, but it seems it is developed by the team of Quart and this is the ASGI your are using here. So, I used Hypercorn as the ASGI production server.
I chose the `python:3.7-slim-buster` Docker image as base because it seems it is the most recent official Python version we can get as `slim-buster` without having to build a custom one.
The entrypoint allows to adapt the configuration file with the integrated environment variables when running the image.
So we can do the following:
Build the image:
```
docker build -t snikket-web-portal -f docker/Dockerfile .
```
Run the image:
```
docker run --rm …
```
=> [Docker] Add Dockerfile

snikket_web/admin.py
Eventually, we need to clear that on the backend, but for now we
deal with it in the frontend.
Bonus: this also optimises the display of the circle by removing
O(n) backend requests.
=> Fix ClientResponseError if a circle has a deleted user

snikket_web/__init__.py
The translation is marked as 100% on Weblate, and user testing confirms it works (when manually configured).
Fixes #60
=> Enable Italian translation by default

snikket_web/__init__.py, snikket_web/invite.py, snikket_web/templates/unauth.html, snikket_web/templates/user_profile.html, snikket_web/translations/messages.pot, snikket_web/user.py
This checks the avatar size on the client side (if available) and
on the server side against a configuration-defined limit. The
default limit is set to use the same value as in the original
report, as no sensible limit value is known.
Fixes #67.
=> Implement size checking for the avatar

snikket_web/prosodyclient.py
mod_rest after the switch to the new util.datamapper in
https://hg.prosody.im/prosody-modules/rev/073f5397c1d2 does not accept
boolean True as value for the xep-0092 'version' field. An empty object
is equivalent and compatible with both previous and future versions.
=> Update for switch to datamapper in mod_rest

snikket_web/admin.py, snikket_web/prosodyclient.py, snikket_web/scss/app.scss, snikket_web/static/img/icons.svg, snikket_web/templates/admin_delete_user.html, snikket_web/templates/admin_edit_circle.html, snikket_web/templates/admin_edit_invite.html, snikket_web/templates/admin_edit_user.html, snikket_web/templates/admin_reset_user_password.html, snikket_web/templates/admin_users.html, snikket_web/templates/user_logout.html, snikket_web/templates/user_passwd.html, snikket_web/templates/user_profile.html, snikket_web/translations/messages.pot, tools/icons.list
**Note:** The "Limited" role is, at the time of writing, **not** supported by Snikket-Server yet, which is why it is disabled in the UI for now. So don’t be confused if you don’t see it in the web UI. #78 tracks reenabling the role. **End note**
* Support for changing the user display name
* Support for displaying the role of users in the listing
* Support for changing the role of a user
Requires [afe80b64e209 in prosody](https://hg.prosody.im/trunk/rev/afe80b64e209) and [d6a3201a65c0 in prosody-modules](https://hg.prosody.im/prosody-modules/rev/d6a3201a65c0).
Includes #75.
Fixes #42.
=> "Edit user" flow, role management

Dockerfile, snikket_web/__init__.py, snikket_web/_version.py
Rather than maintaining a hard-coded version number in the repo (which immediately becomes out of date), read it from a `.app_version` file or (if that's not present) attempt to read from the git repository (if we're in one).
=> Automatically determine version from build info or git

.github/workflows/main.yaml
Otherwise, the toml type hints are missing which mypy does not
like.
=> Install build requirements for mypy CI check

snikket_web/admin.py, snikket_web/templates/admin_edit_circle.html, snikket_web/translations/messages.pot
This helps with removing those users from circles, to avoid them
popping up in peoples roster again.
Even though removal from a circle also only partially works
(roster entries are for instance not cleared), this helps with
ghost users reappearing all the time.
=> admin: Show deleted users in circle members

snikket_web/templates/invite_view.html
The button was broken because it was classified as popover, which
means that the JavaScript code will mess with it. In reality,
*that* button was supposed to point at the actual market:// URL.
So we just remove the class and associated data here to fix that.
Fixes #89.
=> Fix F-Droid installation button

snikket_web/templates/invite_success.html
Someone who registers via the web might also be interested in proceeding to the web portal. Perhaps it's just me as a developer and/or admin.
Suggestions for proper wording, or better solutions would be appreciated.
=> Link to main page after successful registration

requirements.txt
wtforms 3.0 is incompatible with our code. A separate issue will be
filed to address the incompatibilities, but this should be enough to get
working images out of it.
With 3.x, we're seeing:
```
File "/home/horazont/Projects/python/snikket-web-portal/snikket_web/main.py", line 35, in LoginForm
address = wtforms.TextField(
AttributeError: module 'wtforms' has no attribute 'TextField'
```
and the portal fails to start.
=> Pin wtforms to 2.x

.github/workflows/main.yaml, snikket_web/admin.py, snikket_web/user.py
This alerts us of stray print statements, which should never occur
because this is a non-TUI application.
=> Include flake8-print plugin

snikket_web/infra.py
Found in production. Yes really. Due to some borked LXC integration, my
snikket host reports
```
MemTotal:       9007199254740991 kB
MemFree:        9007199254690591 kB
MemAvailable:   9007199254690591 kB
```
That is more than 1024 TiB, so it tries to go further up in the scale,
which then causes a Guru Meditation because of the uncaught IndexError.
=> Fix corner cases of byte number formatting

Dockerfile
Apparently, we managed to publish an image without working aiohttp
because of this.
Partially a regression from 5d7183a.
=> Fix error handling when building image

Dockerfile
Dependencies are not necessarily packaged for all architectures. In some cases
(such as aiohttp, and others, on ARM) pip will attempt to compile the
dependency from scratch. Since switching to multi-stage builds, we have been
installing these without a compiler present which caused the build to fail on
ARM architectures.
This commit temporarily installs build-essential packages while running pip,
then removes them again afterwards.
@horazont Specifically requesting your review because I'm particularly curious some things, such as whether we need to be keeping things like python-setuptools around. I didn't change this behaviour for now, in case it's needed. Also, is hypercorn not in requirements.txt, or why were we (and still are) installing it separately? Now would be a good time to check …
=> Dockerfile: Ensure a compiler is available while pip-installing requirements

Dockerfile
This was missing, required to build. Unlike last night's PR I've actually tested this one on an ARM system :)
=> Dockerfile: Add dev headers required for building deps

Dockerfile
`nc` (from netcat) is required for the healthcheck. In
c1cf6ab1e5f7f9e66d7daf2279d2061d6e02824c, the installation was
erroneously moved to the builder image, instead of the final image, so
it was missing since then from the actual application image, causing it
to always show as unhealthy.
Fixes #126.
=> Install netcat in final image instead of build image

snikket_web/templates/invite_register.html, snikket_web/templates/invite_reset.html, snikket_web/templates/user_passwd.html
This allows user agents to do smart things like filling in the current
password only where it makes sense or integrate nicely with a password
manager.
Fixes #94.
=> Add autocomplete hints to password forms

snikket_web/main.py, snikket_web/templates/about.html
Dependency versions are generally not useful, unless you are developing
or otherwise outside of a normal release situation: If you are on a
normal release, we can figure out the dep versions by looking at the
docker image.
To reduce the amount of information displayed and the amount of
information which needs to be conveyed in case of problems, we only show
the web portal and prosody versions to admins, unless debug mode is
enabled.
The behaviour that versions are only shown to logged in admins (unless
debug mode is enabled) remains unchanged.
Fixes #115.
=> Do not show dependency versions even to admins by default

.github/workflows/main.yaml
Forgetting to run that causes weblate (or other translation tools) to
show outdated strings and not import new strings, which is bad for the
collaboration.
Fixes #118.
=> Add check for a missing `make extract_translations`

snikket_web/infra.py
It was found during testing that some user agents cache aggressively
even between switches of the UI language. To properly indicate that the
pages actually depend on that information, we add the correct Vary
header.
Fixes #106.
=> Add Vary: Accept-Language to all pages using that information

snikket_web/templates/user_manage_data.html
The other user related sections all have a Back button so it makes sense that this one ought to have one as well.
=> Add a Back button from export panel for consistency

snikket_web/__init__.py
It is more likely that a user for whose language no translation exists
can read english than danish.
The fallback to english was apparently introduced in c58ce845, though it
is possible that `best_match` did that internally before.
Fixes #131.
=> Use english as default language instead of danish

babel.cfg, snikket_web/translations/messages.pot
It was broken because of the same jinja2 update (presumably) which
prompted 68f72743c5ee10d23cceae2512e8746a2e9d1b74.
=> Unbreak translation text extraction

requirements.txt
The quart pin is required to fix an attribute error which otherwise occurs during startup. Hence, this should be a good qualifier to know when it's safe to upgrade.
Note that this is not a problem in Quart, but in flask-WTForms. But downgrading flask-wtforms does not help [1], so we don't revert that uprade.
```
AttributeError: module 'quart.json' has no attribute 'JSONEncoder'
```
[1]: https://github.com/pallets/quart/issues/163
=> Update WTForms and pin quart version

snikket_web/prosodyclient.py
Makes portal understand when admin privileges are present on latest Prosody trunk & modules.
Ref https://hg.prosody.im/prosody-modules/rev/5ab134b7e510 and probably other changes to mod_http_oauth2 since (and oh so many changes in Prosody trunk)
Thanks @horazont
=> Update to match new Prosody scope naming scheme

snikket_web/admin.py, snikket_web/prosodyclient.py, snikket_web/templates/admin_edit_user.html
Prosody changed its role scheme to only support a single primary role for each user. In addition, the names of the built-in roles have been changed. We thus follow those changes to be compatible with the most recent trunk.
One open question is whether we should switch admin -> operator here, too (operator being a server-wide admin), but so far there's no need to.
=> Follow new role scheme in Prosody

snikket_web/admin.py, snikket_web/templates/admin_delete_circle.html, snikket_web/templates/admin_edit_circle.html, snikket_web/translations/messages.pot
Deleting a circle is highly destructive. It removes the group chat alongside history, as well as the user list. It should definitely be protected by a confirmation dialogue, I have no clue why it wasn't.
Fixes #153.
=> Add confirmation step to circle deletion

Dockerfile, Makefile, build-requirements.txt, snikket_web/prosodyclient.py, snikket_web/scss/app.scss
No great hurry, but nice to do eventually. Preferably coordinated with similar base image updates of the other Snikket server parts.
If pyScss has a release that includes https://github.com/Kronuz/pyScss/pull/426 then that commit can be dropped.
=> Switch base image to Debian 12

snikket_web/prosodyclient.py
In OAuth 2.0, you don't authenticate with the revocation endpoint using the token you are revoking, but rather the OAuth client credentials.
=> Fix revokation of token on logout

snikket_web/admin.py, snikket_web/infra.py, snikket_web/prosodyclient.py, snikket_web/scss/app.scss, snikket_web/static/img/icons.svg, snikket_web/templates/admin_edit_user.html, snikket_web/templates/admin_users.html, snikket_web/templates/library.j2, snikket_web/translations/messages.pot, tools/icons.list, tools/import-icons.sh
This PR improves a bunch of things related to user management in the web portal.
- The user list now renders profile pictures
- Users are presented in a more compact format, where names and profile picture are grouped together visually in a familiar style
- Last activity is now displayed (with day granularity)
- It show shows when an account is locked or pending deletion, and provides the option to unlock/cancel deletion
- Some smaller UI/UX fixes are also included
The new features require an updated version mod_http_admin_api in prosody-modules, specifically version 5c589fab6f53 or later.
=> Admin user management UI updates (Dec 23)

snikket_web/templates/invite_reset.html, snikket_web/templates/invite_view.html, snikket_web/translations/messages.pot
The QR code stuff was throwing a JS exception, and on other pages we don't even use it.
=> Remove broken/needless JS from certain pages

snikket_web/scss/app.scss, snikket_web/templates/admin_edit_circle.html, snikket_web/templates/library.j2, snikket_web/translations/messages.pot
This improves the display of user profiles in e.g. the user listing by showing the display name more prominently than the username, and expanding the username to the whole JID. See commit message for rationale.
It also switches the circle member listing from the old "username only" format to the new "user with avatar" rendering that we are using in the "manage users" section.
=> Tweak user profile display

snikket_web/admin.py, snikket_web/templates/admin_users.html
Fixes that the _Broadcast message_ form and the _Limited_ role in the user  was not translated, due to mistakenly using `_` (aka `flask_babel.gettext`) instead of `_l` (aka `flask_babel.lazy_gettext`).
Bonus: removal of a stray closing HTML tag without a matching opening tag.
=> Fix incomplete translation of Announcement form and Limited user role

snikket_web/prosodyclient.py
Previously this led to an OAuth grant with an empty scope, which could not be used for anything.
Related to https://github.com/snikket-im/snikket-server/issues/78
=> Fix login for restricted users

snikket_web/invite.py, snikket_web/prosodyclient.py, snikket_web/translations/messages.pot, snikket_web/user.py
An issue was discovered by @Zash where changing the password might fail, but give the user no feedback that it had failed. This could lead to a user thinking their password has been changed, when in fact it has not.
The first commit adds error handling. It's not the best (it throws an XMPP error condition at the user with no explanation), but hopefully we can improve it in the future.
The main reason a password change might fail is because it doesn't meet the policies enforce by the server. For example, if it is too short. The second commit adds some pre-validation before we send it to the server to catch the most common policy violations.
=> Fix password validation

snikket_web/templates/login.html
This typo managed to lurk unnoticed since the initial commit. I guess it didn't cause any harm, but it's time to fix it!
=> templates: Fix typo in closing form tag

snikket_web/admin.py
The role creation appears to fail without an error, only refreshing the page unless a role is selected.
=> Specify a default role in invite form

snikket_web/__init__.py
With 'Secure' set, it may default to 'None', which we don't need or want.
'Strict' is not suitable for session cookies - the user would see the login screen when navigating from another site (e.g. hosting dashboard) and we already have CSRF protection on forms.
=> Explicitly set cookie SameSite attribute to Lax

snikket_web/prosodyclient.py
Varyingly pedantic tweaks to the OAuth client registration data.
- Include web portal version in oauth client registration
- Include requested scopes in oauth client registration
- Declare use of no response types, since password grant uses none
- Declare that oauth client credentials are using POST method
- Declare as a web application in oauth client registration
- Include a software id in oauth client registration
=> OAuth tweaks

Dockerfile
To match https://github.com/snikket-im/snikket-server/pull/266 since it
would look wrong if one service has a health check and not the other.
=> Dockerfile: Remove health check
