snikket-im/snikket-web-portal

snikket_web/prosodyclient.py

Implement token revocation

---

snikket_web/__init__.py
snikket_web/admin.py
snikket_web/prosodyclient.py
snikket_web/templates/admin_reset_user_password.html
snikket_web/templates/admin_users.html
snikket_web/translations/de/LC_MESSAGES/messages.po
snikket_web/translations/en/LC_MESSAGES/messages.po

Add support for password reset links

---

snikket_web/templates/about.html
snikket_web/templates/user_logout.html
snikket_web/templates/user_passwd.html
snikket_web/templates/user_profile.html

I haven’t tested that it does the correct thing.

Make more titles translatable

---

snikket_web/admin.py
snikket_web/templates/admin_users.html

Render invite form below user list

---

snikket_web/admin.py

With https://github.com/snikket-im/snikket-server/issues/37 implemented, unhide the role in the UI.

admin: Show restricted user role in the UI

---

Dockerfile

Built and seems to run without any immediate obvious issues.

Dockerfile: Switch base image to Debian 11

---

snikket_web/invite.py
snikket_web/prosodyclient.py
snikket_web/static/img/icons.svg
snikket_web/templates/invite_success.html
snikket_web/templates/user_home.html
snikket_web/templates/user_manage_data.html
snikket_web/user.py
tools/icons.list

This adds a UI for account export. It currently depends on changes that are not yet in snikket-server (or Prosody!).
Account import will follow, but not here. The plan is to support import as an action on invitations.

Feature: account import/export

---

snikket_web/admin.py
snikket_web/templates/admin_system.html

Requires at least https://hg.prosody.im/prosody-modules/rev/883ad8b0a7c0

Show how much storage space is used by shared files

---

requirements.txt
snikket_web/admin.py
snikket_web/main.py
snikket_web/user.py

Port to WTForms 3.x

---

snikket_web/translations/messages.pot

It diffs the things, and we're in 2023 now.

Fix i18n CI linting

---

snikket_web/invite.py

Fix Link header on invite pages

---

snikket_web/prosodyclient.py

The mod_http_admin_api changed recently [1], so we need to follow suit.
Fixes #149.
[1]: https://hg.prosody.im/prosody-modules/rev/d68348323406

Make AdminUserInfo compatible with new API

---

snikket_web/admin.py
snikket_web/prosodyclient.py
snikket_web/templates/admin_edit_user.html

To deal with [changes to user roles in Prosody](https://hg.prosody.im/trunk/rev/082c7d856e61).
To go with https://github.com/snikket-im/snikket-server/pull/181

Update for role changes in Prosody

---

snikket_web/admin.py
snikket_web/prosodyclient.py
snikket_web/templates/admin_circles.html
snikket_web/templates/admin_create_circle_chat.html
snikket_web/templates/admin_create_circle_group_chat_form.html
snikket_web/templates/admin_edit_circle.html
snikket_web/translations/messages.pot

Part of https://github.com/snikket-im/snikket-server/issues/149

Support circles with multiple group chats, remove default group chat

---

snikket_web/infra.py
snikket_web/prosodyclient.py

- Incorrect translation function used
- Circle group chats with no name raised an error

Fix a couple of runtime errors

---

requirements.txt

Didn't do deep research here, just fitted it against the current Docker image release.

Fix python requirements to actually work

---

snikket_web/prosodyclient.py

Handle broken/incorrect avatar metadata gracefully

---

snikket_web/admin.py
snikket_web/prosodyclient.py
snikket_web/scss/app.scss
snikket_web/static/img/icons.svg
snikket_web/templates/admin_create_invite_form.html
snikket_web/templates/admin_edit_user.html
snikket_web/templates/library.j2
snikket_web/translations/messages.pot
tools/icons.list

Includes some reorganization and prettification of the creation form.
Fixes #178 
Depends on mod_http_admin_api commits [2aa66e928aa0](https://hg.prosody.im/prosody-modules/rev/2aa66e928aa0) (write) and [432efc39572f](https://hg.prosody.im/prosody-modules/rev/432efc39572f) (read).

Allow selecting a role when creating an invitation

---

snikket_web/admin.py

Actually in the invite form this time

Specify a default role in invite form

---

snikket_web/templates/user_home.html
snikket_web/translations/messages.pot

The "Welcome to Snikket!" is not currently translatable, I assume it should be?

Translate welcome message

---

snikket_web/translations/messages.pot
snikket_web/user.py

Fixes #190
The templates appear to handle this being False, so that seems the path
of least resistance.

Ignore that users do not have access to metrics
